services:
  - type: web
    name: demo-spring-boot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: spring.datasource.url
        value: jdbc:postgresql://ep-sparkling-boat-a5itk0n4-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: spring.datasource.username
        value: neondb_owner
      - key: spring.datasource.password
        value: npg_Bhpx7rRa4WSj
      - key: spring.jpa.hibernate.ddl-auto
        value: update
      - key: spring.jpa.database-platform
        value: org.hibernate.dialect.PostgreSQLDialect
